apiVersion: v1
kind: Service
metadata:
  name: procesos-circleci-service
spec:
  type: NodePort
  selector:
    app: procesos-circleci
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
